services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: mohamed
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
    networks:
      - hotel-management
    restart: unless-stopped

networks:
  hotel-management:
    driver: bridge
volumes:
  postgres:
